---
- name: Creating user "{{ user }}" with admin access
  user:
    name: "{{ user }}"
    password: "{{ user | password_hash('sha512') }}"
    generate_ssh_key: true
    ssh_key_passphrase: "secret"
    group: sudo
    shell: /bin/bash
  become_user: root
  become: true