---
- name: Update package cache and install dependencies
  apt:
    name:
      - git
      - curl
      - vim
      - build-essential
      - zlib1g-dev
      - libffi-dev
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - liblzma-dev
    state: present
  become: true
  become_user: root
