---
- name: Update package cache and install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - curl
    - vim
    - build-essential
    - zlib1g-dev
    - libffi-dev
    - libssl-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - liblzma-dev
  become_method: sudo