---
- name: Install pipenv
  pip:
    name: pipenv
    extra_args: --user

- name: Set up bash environment for pipenv
  lineinfile:
    path: ~/.bashrc
    line: "{{ item }}"
  with_items:
    - export PATH="$PATH:$HOME/.local/bin"
    - eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
