---
- name: Check pyenv binary exists
  stat:
    path: ~/.pyenv/bin/pyenv
  register: pyenv_installed

- when: not pyenv_installed.stat.exists
  block:
  - name: Clone Pyenv
    git:
      repo: https://github.com/pyenv/pyenv.git
      dest: ~/.pyenv

  - name: Configure Compile
    command: src/configure
    args:
      chdir: ~/.pyenv

  - name: Compile Pyenv
    command: make -C src
    args:
      chdir: ~/.pyenv

  - name: Set up bash environment for Pyenv
    lineinfile:
      path: ~/.bashrc
      line: "{{ item }}"
    with_items:
      - export PYENV_ROOT="$HOME/.pyenv"
      - command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      - eval "$(pyenv init -)"
